example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog


# TODO: Implement Routings Here
app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import * 
#sesuaikan dengan nama fungsi yang dibuat

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_mywatchlist_by_xml, name='show_mywatchlist_by_xml'),
    path('json/', show_mywatchlist_by_json , name='show_mywatchlist_by_json'),
    path('xml/<int:id>', show_mywatchlist_by_xml_id, name='show_mywatchlist_by_xml_id'),
    path('json/<int:id>', show_mywatchlist_by_json_id, name='show_mywatchlist_by_xml_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *


# TODO: Implement Routings Here
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('addtask/', add_task, name='addtask'),
    path('json/', show_todolist_by_json , name='show_todolist_by_json'),
    path('add/', submit_ajax, name='submit_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.

class WatchlistAbdi(models.Model):
    watched = models.CharField(max_length=10)
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=50)
    review = models.TextField()
    

todolist/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

todolist/forms.py
from dataclasses import field
import imp
from django.forms import ModelForm
from todolist.models import Task

class addTask(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem


# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
    'list_katalog': data_barang_katalog,
    'nama': 'Abdillah Assajjad',
    'NPM' : "2106653571"
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import WatchlistAbdi
from django.http import HttpResponse
from django.core import serializers

data = WatchlistAbdi.objects.all()

# Create your views here.
def show_mywatchlist(request):
    data_film = WatchlistAbdi.objects.all()
    context = {
        'list_film': data_film,
        'nama': 'Abdi'
    }
    return render(request, "mywatchlist.html", context)

def show_mywatchlist_by_xml(request):
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_mywatchlist_by_json(request):
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_mywatchlist_by_xml_id(request, id):
    dataid = WatchlistAbdi.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", dataid), content_type="application/xml")

def show_mywatchlist_by_json_id(request, id):
    dataid = WatchlistAbdi.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", dataid), content_type="application/json")

todolist/views.py
import datetime
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from todolist.models import Task
from django.contrib.auth.decorators import login_required
from todolist.forms import addTask


# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    #data_todolist = Task.objects.filter(user = request.user)
    context = {
    # 'todolist': data_todolist,
    'nama': 'Abdillah Assajjad',
    'NPM' : "2106653571",
    'username': request.COOKIES['username'],
    }
    return render(request, "todolist_ajax.html", context)

def submit_ajax(request):
    print('sdasdqwe')
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(user = request.user, title = title, description = description)
        new_task.save()
    return HttpResponse('')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('username', username) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

def add_task(request):
    #print(request.POST)
    
    Task = addTask( request.POST)
    if Task.is_valid():
        Temp = Task.save(commit=False)
        Temp.user = request.user
        Temp.save()
        return HttpResponseRedirect('/todolist')
    context = { 'Task':Task }
    return render(request, 'addtask.html', context)

def show_todolist_by_json(request):
    data = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{NPM}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in list_katalog %}
        <tr>
            <th>{{katalog.item_name}}</th>
            <th>{{katalog.item_price}}</th>
            <th>{{katalog.item_stock}}</th>
            <th>{{katalog.description}}</th>
            <th>{{katalog.rating}}</th>
            <th>{{katalog.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

{% block content %}
<h10>Abdi's Watchlist </h10>
<p></p>

<table>
    <tr>
    <th>Status Tonton</th>
    <th>Judul Film</th>
    <th>Nilai</th>
    <th>Tanggal Rilis</th>
    <th>Review</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for film in list_film %}
    <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>        
    </tr>
{% endfor %}
</table>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/addtask.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  	<meta charset="UTF-8">
  	<title>CodePen - A Pen by Mohithpoojary</title>
  	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.2.0/css/all.css'>
	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.2.0/css/fontawesome.css'>
	<link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<!-- partial:index.partial.html -->
<div class="container">
	<div class="screen">
		<div class="screen__content" style="width: 400px;">
			<form class="login"action="" method="POST">
                {% csrf_token %}
                {{Task}}
				<button class="button login__submit">
					<span class="button__text"><input type="submit" name="Submit" placeholder="Add"></span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>				
			</form>
			<div class="social-login">
			</div>
		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>		
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>		
	</div>
</div>
<!-- partial -->
  
</body>
</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<section class="h-100 gradient-form">
	<div class="container py-5 h-100">
	  <div class="row d-flex justify-content-center align-items-center h-100">
		<div class="col-xl-10">
		  <div class="card rounded-3 text-black">
			<div class="row g-0">
			  <div class="p-md-5">
				<div class="card-body p-md-5 mx-md-4">
				  <div class="text-center">
					<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
					  style="width: 185px;" alt="logo">
					<h4 class="mt-1 mb-5 pb-1"></h4>
				  </div>
  
				  <form method="POST" action="">
					{% csrf_token %}
					<p>Please login to your account</p>
  
					<div class="form-outline mb-4">
						<input type="text" name="username" placeholder="Username" class="form-control">
					  <label class="form-label" for="form2Example11">Username</label>
					</div>
  
					<div class="form-outline mb-4">
						<input type="password" name="password" placeholder="Password" class="form-control">
					  <label class="form-label" for="form2Example22">Password</label>
					</div>
  
					<div class="text-center pt-1 mb-5 pb-1">
					  <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">
						<input class="btn login_btn" type="submit" value="Login"></button>
					</div>
  
					<div class="d-flex align-items-center justify-content-center pb-4">
					  <p class="mb-0 me-2">Don't have an account?</p>
					  <button type="button" class="btn btn-outline-danger " ><a href="{% url 'todolist:register' %}">Create New</a></button>
					</div>
  
				  	</form>
				  	{% if messages %}
						<ul>
							{% for message in messages %}
								<li>{{ message }}</li>
							{% endfor %}
						</ul>
					{% endif %} 
  
				</div>
			  </div>
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </section>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Sign Up</title>
{% endblock meta %}

{% block content %}  

<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body text-center justify-content-center align-items-center">
  
              <a class="navbar-brand" href="#"><h1>Sign Up</h1></a>
              <form method="POST" style="margin-top: 30px;">  
                {% csrf_token %}  
              <div class="form-outline mb-4">
                {{ form.as_table }} 
                
                <div class="text-center pt-1 mb-5 pb-1">
                  <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">
                  <input class="btn btn-primary btn-block fa-lg gradient-custom-2 " type="submit" name="submit" value="Register"/></button>
                </div>
              </div>
              
              </form>
              {% if messages %}  
                    <ul>   
                        {% for message in messages %}  
                            <li>{{ message }}</li>  
                            {% endfor %}  
                    </ul>   
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist</title>
{% endblock meta %}

{% block content %}
 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="collapse navbar-collapse" id="ftco-nav">
    <a class="navbar-brand" href="#"><h1>Tugas 4 Assignment PBP</h1></a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a href="{% url 'todolist:addtask' %}" class="nav-link">Add Task</a></li>
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'todolist:logout' %}" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Log Out</a>
      </li>
    </ul>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>


  <h5>UserName: </h5>
  <p>{{username}}</p>

  <div class="table-wrap">
    <table class="table table-responsive-xl">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>Tanggal Pembuatan Task</th>
          <th>Judul Task</th>
          <th>Deskripsi Task</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        {% for list in todolist %}
    
        <tr class="alert" role="alert">
          <td>
            <label class="checkbox-wrap checkbox-primary">
              <input type="checkbox" checked>
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="d-flex align-items-center">
            <div class="img" style="background-image: url(images/person_1.jpg);"></div>
            <div class="pl-3 email">
              <span>{{ list.date }} </span>
              <span></span>
            </div>
          </td>
          <td>{{ list.title }}</td>
          <td class="status"><span class="active">{{ list.description }}</span></td>
          <td>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="fa fa-close"></i></span>
            </button>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>

  


    {% comment %} Add the data below this line {% endcomment %}
    <div class="d-flex flex-row">
    {% for list in todolist %}
        <div class="card flex-row" style="width: 18rem; margin: 2px;">
          <div class="card-body">
            <h5 class="card-title">{{list.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{list.date}}</h6>
            <p class="card-text">{{list.description}}</p>
          </div>
        </div>
    {% endfor %}
    
    </div>
  

 
 {% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist</title>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.2.0/css/all.css'>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.2.0/css/fontawesome.css'>
<script>
    $(document).ready(function(){
        $.get("{% url 'todolist:show_todolist_by_json' %}", function(data){
            var content = `
            <table class="table table-responsive-xl">
                <thead>
                    <tr>
                    <th>&nbsp;</th>
                    <th>Tanggal Pembuatan Task</th>
                    <th>Judul Task</th>
                    <th>Deskripsi Task</th>
                    <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
            `;
            for(var i = 0; i < data.length; i++){
                content += `
                <tr class="alert" role="alert">
                    <td>
                        <label class="checkbox-wrap checkbox-primary">
                        <input type="checkbox" checked>
                        <span class="checkmark"></span>
                        </label>
                    </td>
                    <td class="d-flex align-items-center">
                        <div ></div>
                        <div class="pl-3 email">
                        <span>${data[i].fields.date} </span>
                        <span></span>
                        </div>
                    </td>
                    <td>${data[i].fields.title}</td>
                    <td class="status"><span class="active">${data[i].fields.description}</span></td>
                    <td>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>
                        </button>
                    </td>
                    </tr>
                `
            }
            content += `
                </tbody>
            </table>
            `
            $('section').html(content);
        })
        $.get('/todolist/json/', function(data){
            var card = `
            <div class="d-flex flex-row">
            `
            for (var i = 0; i < data.length; i++){
                card += `
                <div class="card flex-row" style="width: 18rem; margin: 2px;">
                    <div class="card-body">
                        <h5 class="card-title">${data[i].fields.title}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">${data[i].fields.date}</h6>
                        <p class="card-text">${data[i].fields.description}</p>
                    </div>
                </div>
                `
            }
            card += '</div>'
            $('#cardds').html(card)
        })
    })
 

 </script>
{% endblock meta %}

{% block content %}
 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="collapse navbar-collapse" id="ftco-nav">
    <a class="navbar-brand" href="#"><h1>Tugas 4 Assignment PBP</h1></a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Task</a></li>
      <li class="nav-item active">
        <a> s</a>
        <container>
          <a class="btn btn-primary " href="{% url 'todolist:logout' %}" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Log Out</a>
        </container>
      </li>
    </ul>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>


  <h5>UserName: </h5>
  <p>{{username}}</p>

  <section>p</section>

  {% comment %} Add the data below this line {% endcomment %}
    <div id="cardds" class="d-flex flex-row">  
    </div>


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form class="login"action="" method="POST">
          {% csrf_token %}
          <h1 class="font-bold font-5xl">ADD TODOLIST</h1>
            <div class="flex flex-row">
                <label for="title" class="mb-2 font-5xl">Title</label>
                <a class="" style="color: #FFF;">ssss</a>
                <input type="text" name="title" id="title" placeholder="Title" required>
            </div>
            <div class="flex flex-row">
                <label for="description" class="mb-2 font-5xl">Description</label>
                <textarea name="deskripsi" id="deskripsi" cols="23" placeholder="deskripsi" required></textarea>
            </div>
        </form>
        <button id="Submit-Button" class="login__submit" data-bs-dismiss="modal">
            <span class="button__text">Add</span>
            <i class="button__icon fas fa-chevron-right"></i>
            <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
        </button>		
      </div>
    </div>
  </div>
</div>

  <!-- <div class="table-wrap">
    <table class="table table-responsive-xl">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>Tanggal Pembuatan Task</th>
          <th>Judul Task</th>
          <th>Deskripsi Task</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        {% for list in todolist %}
    
        <tr class="alert" role="alert">
          <td>
            <label class="checkbox-wrap checkbox-primary">
              <input type="checkbox" checked>
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="d-flex align-items-center">
            <div class="img" style="background-image: url(images/person_1.jpg);"></div>
            <div class="pl-3 email">
              <span>{{ list.date }} </span>
              <span></span>
            </div>
          </td>
          <td>{{ list.title }}</td>
          <td class="status"><span class="active">{{ list.description }}</span></td>
          <td>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="fa fa-close"></i></span>
            </button>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div> -->

<script>
    $(document).ready(function(){
        $('#Submit-Button').click(function(){
            var Title = document.getElementById('title').value;
            var Description = $('#deskripsi').val();
            var CSRFtoken = $('input[name="csrfmiddlewaretoken"]').val();
            $.post('/todolist/add/', {
                description: Description,
              
                title: Title,
                
                csrfmiddlewaretoken: CSRFtoken,
            }, function(){
              $('section').empty();
              $.get("{% url 'todolist:show_todolist_by_json' %}", function(data){
            var content = `
            <table class="table table-responsive-xl">
                <thead>
                    <tr>
                    <th>&nbsp;</th>
                    <th>Tanggal Pembuatan Task</th>
                    <th>Judul Task</th>
                    <th>Deskripsi Task</th>
                    <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
            `;
            for(var i = 0; i < data.length; i++){
                content += `
                <tr class="alert" role="alert">
                    <td>
                        <label class="checkbox-wrap checkbox-primary">
                        <input type="checkbox" checked>
                        <span class="checkmark"></span>
                        </label>
                    </td>
                    <td class="d-flex align-items-center">
                        <div></div>
                        <div class="pl-3 email">
                        <span>${data[i].fields.date} </span>
                        <span></span>
                        </div>
                    </td>
                    <td>${data[i].fields.title}</td>
                    <td class="status"><span class="active">${data[i].fields.description}</span></td>
                    <td>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>
                        </button>
                    </td>
                    </tr>
                `
            }
            content += `
                </tbody>
            </table>
            `
            $('section').html(content);
        })
        $('#cardds').empty();
        $.get('/todolist/json/', function(data){
            var card = `
            <div class="d-flex flex-row">
            `
            for (var i = 0; i < data.length; i++){
                card += `
                <div class="card flex-row" style="width: 18rem; margin: 2px;">
                    <div class="card-body">
                        <h5 class="card-title">${data[i].fields.title}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">${data[i].fields.date}</h6>
                        <p class="card-text">${data[i].fields.description}</p>
                    </div>
                </div>
                `
            }
            card += '</div>'
            $('#cardds').html(card)
        })
            })
        })
    })
</script>


    
  

 

 {% endblock content %}